#Importing data from keras.datasets

In [2]:
from keras.datasets import cifar10 

Using TensorFlow backend.


##Splitting the data into train and test data 


In [3]:
(X_train,Y_train),(X_test,Y_test)=cifar10.load_data()

170500096/170498071 [==============================] - 19s 0us/step


## Shape of the data 

In [4]:
print(X_train.shape) 
print(X_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(50000, 32, 32, 3)
(10000, 32, 32, 3)
(50000, 1)
(10000, 1)


### This shows that training data has 50000 images of size (32x32x3):(height,width,depth)
### Testing data has 10000 images of size (32x32x3):(height,width,depth)
### Y_train and Y_test are the labels for the training and testing data 

In [5]:
print(X_train[0])        # Images are in the form of three dimensional arrays 

[[[ 59  62  63]
  [ 43  46  45]
  [ 50  48  43]
  ...
  [158 132 108]
  [152 125 102]
  [148 124 103]]

 [[ 16  20  20]
  [  0   0   0]
  [ 18   8   0]
  ...
  [123  88  55]
  [119  83  50]
  [122  87  57]]

 [[ 25  24  21]
  [ 16   7   0]
  [ 49  27   8]
  ...
  [118  84  50]
  [120  84  50]
  [109  73  42]]

 ...

 [[208 170  96]
  [201 153  34]
  [198 161  26]
  ...
  [160 133  70]
  [ 56  31   7]
  [ 53  34  20]]

 [[180 139  96]
  [173 123  42]
  [186 144  30]
  ...
  [184 148  94]
  [ 97  62  34]
  [ 83  53  34]]

 [[177 144 116]
  [168 129  94]
  [179 142  87]
  ...
  [216 184 140]
  [151 118  84]
  [123  92  72]]]


## Normalizing the pixel value
### Changing the range of pixel values from (0-255) to (0-1)

In [0]:
X_train=X_train/255.0
X_test=X_test/255.0

In [7]:
print(X_train[0])            # pixel values are in the range (0-1)

[[[0.23137255 0.24313725 0.24705882]
  [0.16862745 0.18039216 0.17647059]
  [0.19607843 0.18823529 0.16862745]
  ...
  [0.61960784 0.51764706 0.42352941]
  [0.59607843 0.49019608 0.4       ]
  [0.58039216 0.48627451 0.40392157]]

 [[0.0627451  0.07843137 0.07843137]
  [0.         0.         0.        ]
  [0.07058824 0.03137255 0.        ]
  ...
  [0.48235294 0.34509804 0.21568627]
  [0.46666667 0.3254902  0.19607843]
  [0.47843137 0.34117647 0.22352941]]

 [[0.09803922 0.09411765 0.08235294]
  [0.0627451  0.02745098 0.        ]
  [0.19215686 0.10588235 0.03137255]
  ...
  [0.4627451  0.32941176 0.19607843]
  [0.47058824 0.32941176 0.19607843]
  [0.42745098 0.28627451 0.16470588]]

 ...

 [[0.81568627 0.66666667 0.37647059]
  [0.78823529 0.6        0.13333333]
  [0.77647059 0.63137255 0.10196078]
  ...
  [0.62745098 0.52156863 0.2745098 ]
  [0.21960784 0.12156863 0.02745098]
  [0.20784314 0.13333333 0.07843137]]

 [[0.70588235 0.54509804 0.37647059]
  [0.67843137 0.48235294 0.16470588]


In [8]:
# Shape of the images 
X_train.shape[1:]

(32, 32, 3)

### Checking the labels of the data 

In [9]:
print(Y_train) 

type(Y_train)

[[6]
 [9]
 [9]
 ...
 [9]
 [1]
 [1]]


numpy.ndarray

In [10]:
Y_train[0]

array([6], dtype=uint8)

## Labels are in the form of 1D array

### Labels are in the form of integers from 0-9 as there are 10 classes.
### We have to convert it into one hot vector (i.e vector of length 10).
###[0 0 0 0 0 0 1 0 0 0]  This is one hot vector for label 6.
here class 6 is the label so 1 is stored at sixth index.

In [0]:
# Keras provides the function (to_categorical) to do one hot encoding 
from keras.utils import np_utils

Y_train=np_utils.to_categorical(Y_train)
Y_test=np_utils.to_categorical(Y_test)

In [12]:
Y_train[0]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)

We can see that the label has been changed from 1D to 10D array.

# Model using Keras 

##Importing libraries

In [0]:
from keras.models import Sequential
from keras import layers 

### Creating Variables 

### Batch_size -
batch_size is the number of input samples that will be propogated through the network.
For instance, let's say you have 1000 training samples and you want to set up a batch_size equal to 100. The algorithm takes the first 100 samples (from 1st to 100th) from the training dataset and trains the network(updates weights and biases). Next it takes the second 100 samples (from 101st to 200th) and trains the network again. It will have to go through 10 iterations to train the whole dataset. We normally set the batch_size in the powers of 2 like 64, 128, 256 etc because it fits right in the memory of  the CPU or GPU.

### Epochs-
One Epoch is when an ENTIRE dataset is passed forward and backward through the neural network only ONCE.

Since one epoch is too big to feed to the computer at once we divide it in several smaller batches.



In [0]:
batch_size = 256
epochs = 20
num_classes = 10    # number of classes in the dataset 

### Model

### Sequential model
The Sequential model is a linear stack of layers.

We can add layers by using .add() method.


In [0]:
model = Sequential()

model.add(layers.Conv2D(32, (3,3), padding='same', activation = 'relu', input_shape = X_train.shape[1:]))

model.add(layers.Conv2D(64, (3,3), activation = 'relu'))

model.add(layers.MaxPooling2D((2,2)))

model.add(layers.Conv2D(64, (3,3), activation = 'relu'))

model.add(layers.MaxPooling2D((2,2)))

model.add(layers.Dropout(0.25))


model.add(layers.Conv2D(128, (3,3), activation = 'relu'))

model.add(layers.MaxPooling2D((2,2)))

model.add(layers.Dropout(0.25))


model.add(layers.Flatten())

model.add(layers.Dense(512, activation = 'relu'))

model.add(layers.Dense(256, activation = 'relu'))

model.add(layers.Dense(num_classes, activation ='softmax'))


In [33]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_49 (Conv2D)           (None, 32, 32, 32)        896       
_________________________________________________________________
conv2d_50 (Conv2D)           (None, 30, 30, 64)        18496     
_________________________________________________________________
max_pooling2d_40 (MaxPooling (None, 15, 15, 64)        0         
_________________________________________________________________
conv2d_51 (Conv2D)           (None, 13, 13, 64)        36928     
_________________________________________________________________
max_pooling2d_41 (MaxPooling (None, 6, 6, 64)          0         
_________________________________________________________________
dropout_15 (Dropout)         (None, 6, 6, 64)          0         
_________________________________________________________________
conv2d_52 (Conv2D)           (None, 4, 4, 128)         73856     
__________

## Compiling the model 

In [0]:
from keras.optimizers import rmsprop

model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])


## Training the model 

In [35]:
model.fit(X_train, Y_train, 
          batch_size = batch_size, 
          epochs = epochs, 
          validation_data=(X_test, Y_test), 
          shuffle=True)

Instructions for updating:
Use tf.cast instead.
Train on 50000 samples, validate on 10000 samples
Epoch 1/20
50000/50000 [==============================] - 296s 6ms/step - loss: 1.7373 - acc: 0.3513 - val_loss: 1.4004 - val_acc: 0.4874
Epoch 2/20
50000/50000 [==============================] - 295s 6ms/step - loss: 1.3256 - acc: 0.5174 - val_loss: 1.1880 - val_acc: 0.5731
Epoch 3/20
50000/50000 [==============================] - 296s 6ms/step - loss: 1.1511 - acc: 0.5863 - val_loss: 1.0423 - val_acc: 0.6353
Epoch 4/20
50000/50000 [==============================] - 296s 6ms/step - loss: 1.0309 - acc: 0.6336 - val_loss: 0.9311 - val_acc: 0.6752
Epoch 5/20
50000/50000 [==============================] - 295s 6ms/step - loss: 0.9328 - acc: 0.6695 - val_loss: 0.8850 - val_acc: 0.6862
Epoch 6/20
50000/50000 [==============================] - 295s 6ms/step - loss: 0.8764 - acc: 0.6883 - val_loss: 0.8205 - val_acc: 0.7105
Epoch 7/20
50000/50000 [==============================] - 295s 6ms/step - 

##Testing the Model 

In [36]:
results = model.evaluate(X_test,Y_test)

print('Test loss : ',results[0])
print('Test accuracy : ',results[1])

10000/10000 [==============================] - 17s 2ms/step
Test loss :  0.6001823296546936
Test accuracy :  0.795
